export const publicBookColumns = [
  { key: 'id_buku', label: 'ID Buku' },
  { key: 'isbn', label: 'ISBN' },
  { key: 'judul_buku', label: 'Judul' },
  { key: 'id_kategori_buku', label: 'Jenis' },
  { key: 'id_penulis_buku', label: 'Penulis' },
  { key: 'id_penerbit_buku', label: 'Penerbit' },
  { key: 'tahun_terbit', label: 'Tahun' },
  { key: 'stok_buku', label: 'Stok' },
]

export const resourceConfigs = {
  jenisBuku: {
    title: 'Kelola Jenis Buku',
    description: 'CRUD kategori jenis buku.',
    queryKey: 'jenis-buku',
    apiKey: 'jenisBukuApi',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jenis_buku', label: 'Jenis Buku' },
      { key: 'deskripsi', label: 'Deskripsi' },
    ],
    fields: [
      { name: 'id', label: 'ID Jenis', type: 'text', required: true, minLength: 26, modes: ['edit'], readOnly: true },
      { name: 'jenis_buku', label: 'Jenis Buku', type: 'text', required: true, minLength: 3 },
      { name: 'deskripsi', label: 'Deskripsi', type: 'textarea', required: true, minLength: 3, fullWidth: true },
    ],
    deletePayloadKey: 'id',
  },
  penulis: {
    title: 'Kelola Penulis Buku',
    description: 'CRUD data penulis buku.',
    queryKey: 'penulis-buku',
    apiKey: 'penulisApi',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'penulis_buku', label: 'Penulis' },
      { key: 'alamat', label: 'Alamat' },
      { key: 'email_penulis', label: 'Email' },
      { key: 'deskripsi', label: 'Deskripsi' },
    ],
    fields: [
      { name: 'id', label: 'ID Penulis', type: 'text', required: true, minLength: 26, modes: ['edit'], readOnly: true },
      { name: 'penulis_buku', label: 'Nama Penulis', type: 'text', required: true, minLength: 3 },
      { name: 'alamat_penulis', label: 'Alamat', type: 'text', required: true, minLength: 3 },
      { name: 'email_penulis', label: 'Email', type: 'text', required: true, format: 'email' },
      { name: 'deskripsi', label: 'Deskripsi', type: 'textarea', required: true, minLength: 3, fullWidth: true },
    ],
    mapEditValues: (row) => ({
      id: row.id,
      penulis_buku: row.penulis_buku,
      alamat_penulis: row.alamat || row.alamat_penulis,
      email_penulis: row.email_penulis,
      deskripsi: row.deskripsi,
    }),
    deletePayloadKey: 'id',
  },
  penerbit: {
    title: 'Kelola Penerbit Buku',
    description: 'CRUD data penerbit buku.',
    queryKey: 'penerbit-buku',
    apiKey: 'penerbitApi',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'penerbit_buku', label: 'Penerbit' },
      { key: 'alamat_penerbit', label: 'Alamat' },
      { key: 'telp_penerbit', label: 'Telepon' },
      { key: 'email_penerbit', label: 'Email' },
      { key: 'deskripsi_penerbit', label: 'Deskripsi' },
    ],
    fields: [
      { name: 'id', label: 'ID Penerbit', type: 'text', required: true, minLength: 26, modes: ['edit'], readOnly: true },
      { name: 'penerbit_buku', label: 'Nama Penerbit', type: 'text', required: true, minLength: 3 },
      { name: 'alamat_penerbit', label: 'Alamat', type: 'text', required: true, minLength: 3 },
      { name: 'telp_penerbit', label: 'Telepon', type: 'text', required: true, minLength: 3 },
      { name: 'email_penerbit', label: 'Email', type: 'text', required: true, format: 'email' },
      { name: 'deskripsi', label: 'Deskripsi', type: 'textarea', required: true, minLength: 3, fullWidth: true },
    ],
    mapEditValues: (row) => ({
      id: row.id,
      penerbit_buku: row.penerbit_buku,
      alamat_penerbit: row.alamat_penerbit,
      telp_penerbit: row.telp_penerbit,
      email_penerbit: row.email_penerbit,
      deskripsi: row.deskripsi_penerbit || row.deskripsi,
    }),
    deletePayloadKey: 'id',
  },
  peminjaman: {
    title: 'Kelola Peminjaman',
    description: 'CRUD data peminjaman.',
    queryKey: 'peminjaman',
    apiKey: 'peminjamanApi',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'id_anggota', label: 'ID Anggota' },
      { key: 'tgl_pinjam', label: 'Tanggal Pinjam', type: 'date' },
      { key: 'tgl_hrs_kembali', label: 'Tanggal Kembali', type: 'date' },
      { key: 'jaminan', label: 'Jaminan' },
    ],
    fields: [
      { name: 'id_peminjaman', label: 'ID Peminjaman', type: 'text', required: true, minLength: 26, modes: ['edit'], readOnly: true },
      {
        name: 'id_anggota',
        label: 'ID Anggota',
        type: 'text',
        required: true,
        minLength: 26,
        placeholder: 'Masukkan ID anggota yang valid',
        suggestionSource: 'knownAnggota',
      },
      { name: 'tgl_pinjam', label: 'Tanggal Pinjam', type: 'datetime', required: true },
      { name: 'tgl_hrs_kembali', label: 'Tanggal Harus Kembali', type: 'datetime', required: true },
      { name: 'jaminan', label: 'Jaminan', type: 'text', required: true, minLength: 1 },
    ],
    mapEditValues: (row) => ({
      id_peminjaman: row.id,
      id_anggota: row.id_anggota,
      tgl_pinjam: row.tgl_pinjam,
      tgl_hrs_kembali: row.tgl_hrs_kembali,
      jaminan: row.jaminan,
    }),
    deletePayloadKey: 'id_peminjaman',
    viewPathBuilder: (row) => `/admin/peminjaman/${row.id}`,
  },
  denda: {
    title: 'Kelola Denda',
    description: 'CRUD data denda.',
    queryKey: 'denda',
    apiKey: 'dendaApi',
    columns: [
      { key: 'id_denda', label: 'ID Denda' },
      { key: 'jumlah_denda', label: 'Jumlah' },
      { key: 'id_peminjaman', label: 'Peminjaman' },
      { key: 'id_anggota', label: 'Anggota' },
      { key: 'tgl_pinjam', label: 'Pinjam', type: 'date' },
      { key: 'tgl_hrs_kembali', label: 'Harus Kembali', type: 'date' },
      { key: 'tgl_kembali', label: 'Kembali', type: 'date' },
    ],
    fields: [
      { name: 'id_denda', label: 'ID Denda', type: 'text', required: true, minLength: 26, modes: ['edit'], readOnly: true },
      { name: 'jumlah_denda', label: 'Jumlah Denda', type: 'number', required: true },
      { name: 'tgl_pinjam', label: 'Tanggal Pinjam', type: 'datetime', omitWhenEmpty: true },
      { name: 'tgl_hrs_kembali', label: 'Tanggal Harus Kembali', type: 'datetime', omitWhenEmpty: true },
      { name: 'tgl_kembali', label: 'Tanggal Kembali', type: 'datetime', omitWhenEmpty: true },
      { name: 'id_peminjaman', label: 'ID Peminjaman', type: 'select', required: true, optionsSource: 'peminjaman' },
      {
        name: 'id_anggota',
        label: 'ID Anggota',
        type: 'text',
        required: true,
        readOnly: true,
        placeholder: 'Akan terisi otomatis dari peminjaman',
      },
    ],
    mapEditValues: (row) => ({
      id_denda: row.id_denda,
      jumlah_denda: row.jumlah_denda,
      tgl_pinjam: row.tgl_pinjam,
      tgl_hrs_kembali: row.tgl_hrs_kembali,
      tgl_kembali: row.tgl_kembali,
      id_peminjaman: row.id_peminjaman,
      id_anggota: row.id_anggota,
    }),
    deletePayloadKey: 'id_denda',
  },
}
